### PR TITLE
Let Travis always test last openfisca-core version

### PR DESCRIPTION
**Pull request by maukoquiroga**

### CODE REVIEW

**Comment by benjello** [comment]
@maukoquiroga : this will use the last version of core everytime I test openfisca-survey-manager but I would like to trigger the tests every time a change is made to openfisca-core !

**Comment by maukoquiroga** [comment]
@benjello That should do.

Note that I had to rebase `input_dtataframe_by_entity_by_period`. Try in your console :

    git add -A
    git stash
    git checkout master
    git branch -D input_dtataframe_by_entity_by_period
    git fetch --all
    git checkout input_dtataframe_by_entity_by_period
    git pull origin input_dtataframe_by_entity_by_period

**Comment by maukoquiroga** [comment]
> @maukoquiroga : this will use the last version of core everytime I test openfisca-survey-manager but I would like to trigger the tests every time a change is made to openfisca-core !

That's another thing! 

A poorman's solution for now: I went to https://travis-ci.org/openfisca/openfisca-survey-manager/settings and added

capture d ecran 2018-06-12 a 11 01 57

That means a build will run every 24h unless another build has been triggered within the last 24h.

Feel free to edit it to suit your needs.

**Comment by benjello** [comment]
Thanks @maukoquiroga !

**Pull request merged**
