### PR TITLE
WIP: Test Instant.period deprecation

### PR DESCRIPTION
**Pull request by benjello**
#### Technical changes

- Bump openfisca-core version

### CODE REVIEW

**Comment by benjello** [comment]
Hello @maukoquiroga : I am trying to test the incidence of  https://github.com/openfisca/openfisca-survey-manager/pull/235 on survey-manager.

Could you help me understand why the tests fail ! Thanks !

cc @benoit-cty (I can't reproduce what you got here)

**Comment by benoit-cty** [comment]
I think you have to clear the cache of Github Actions.

Unfortunately, it is not easy : https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#managing-caches

**Comment by benjello** [comment]
@benoit-cty : what about closing and reopening a new PR with a new branch ?

**Comment by benoit-cty** [comment]
Solved using Github CLI to delete the cache:
`gh actions-cache delete "build-/opt/hostedtoolcache/Python/3.8.9/x64-dea13c995191cc25a9962aa1df61773f8b100e351f270afe602736b773cfd46d-e44fa890247a9cb57e4c630649f1b2486ea7e279-ubuntu-latest"`

**Pull request closed without merging**
