### PR TITLE
Correction function compute_pivot_tables in ReformScenario

### PR DESCRIPTION
**Pull request by Lolajossipp**
Correction function `compute_pivot_tables` in ReformScenario

### CODE REVIEW

**Review by sylvainipp — APPROVED** [review]

**Comment by clallemand** [comment]
@benjello could you have a look to this PR ?

**Comment by benjello** [comment]
There is obviously an error.
Thanks @Lolajossipp  for catching it ! 😃

But the fix might not work if you use a `ReformScenario` without a reform simulation.  
So you may want to use `_get_simulation` method to access the `Simulation` instances and use `Simulation.compute_pivote_table` to compute the pivot table.

Hope it helps.

**Comment by benjello** [comment]
@Lolajossipp : you also add a specific test reproducing your use case.

**Comment by Lolajossipp** [comment]
@clallemand

**Review by benjello — APPROVED** [review]
L'idéal pour un test est d'avoir un `assert` pour tester spécifiquement un point.
Après si le temps presse ...

**Review by clallemand — APPROVED** [review]

**Comment by benjello** [comment]
@Lolajossipp : I had in mind adding an `assert` in the test you wrote. But it is not very important, you can move on and merge this PR if you are in a hurry.

**Pull request merged**
